### ISSUE TITLE
German message when deleting a media file

### ISSUE THREAD

**Issue by hay** [scrollytelling/app#1]
When i upload media files in the editor, then try to delete them i get a "Datei wirklich wirklich löschen?" message, even if the setting is English.

**Comment by tilsammans** [comment]
Thanks Hay, it's probably the cache issue from https://github.com/fnando/i18n-js/issues/306

I will clear the server cache.

**Comment by hay** [comment]
Do you think this is the same problem?

<img width="420" alt="screen shot 2015-09-15 at 14 26 12" src="https://cloud.githubusercontent.com/assets/129681/9875333/c7bbc0be-5bb5-11e5-9d4b-8f25acfe9055.png">

**Comment by tilsammans** [comment]
Actually, we're currently tracking the `master` branch of Pageflow, so the translations are just missing I think. Once we're back on a released version I will make sure to add in the missing translations. The new Pageflow release should be imminent. I'll update this ticket once it's live. Until that time I might have to ask you to live with the missing translations.

**Comment by hay** [comment]
I can live with missing translations ;). Thanks for the update!

**Comment by tilsammans** [comment]
They're all better now. Thank you for reporting the issue.

**Comment by hay** [comment]
Awesome, thanks!
