### ISSUE TITLE
Error: The YouTube player is not attached to the DOM.

### ISSUE THREAD

**Issue by tilsammans** [scrollytelling/app#14]
https://sentry.io/space-babies/scr/issues/345031794/

```
Error: The YouTube player is not attached to the DOM.
  at W.f.C (/yts/jsbin/www-widgetapi-vflWgX7t4/www-widgetapi.js:120:224)
  at Array.forEach (<anonymous>)
  at Array.forEach.d (/yts/jsbin/www-widgetapi-vflWgX7t4/www-widgetapi.js:19:177)
  at S.g (/yts/jsbin/www-widgetapi-vflWgX7t4/www-widgetapi.js:142:241)
  at g (/yts/jsbin/www-widgetapi-vflWgX7t4/www-widgetapi.js:94:28)
...
(1 additional frame(s) were not displayed)
```

**Comment by tilsammans** [comment]
Pinging @tf 

If you happen to know why this happens, that would be very welcome news. This error was raised on the editor-screen for an Embedded Video page.

**Comment by tf** [comment]
Have not seen that one before. When does it happen exactly? Does it break the page or the editor? I always see a whole bunch of cross origin related errors, but they never caused any problems for us.

**Comment by ZeeshanFaiz** [comment]
I have encounter this error now as well. I'm using the same code but it do work on the main home page of the website. But when I choose the video section that is being loaded with ajax, my code throw this error 
`Uncaught Error: The YouTube player is not attached to the DOM.`
Maybe loading with ajax is causing this. But don't know what the real problem is

**Comment by tilsammans** [comment]
It seems to originate with Chrome 60 and the YouTube script. It's not under our control.

**Comment by jordanjoecooper** [comment]
@tilsammans  I dont suppose you found out any more info on this particular error ? Came across it myself recently and cant figure out what is causing it.

**Comment by tilsammans** [comment]
@T4JC no, I don't have anything new to report unfortunately.
