### ISSUE TITLE
pageflow_chart Problems

### ISSUE THREAD

**Issue by RonFire** [scrollytelling/app#15]
Hey tilsammans,

i found a link to your code from the pageflow github and hope for maybe some help from you.
I am currently struggling to include the pageflow_chart page_type. 
I can choose the page-type but as soon as i try to upload a datawrapper chart i see this error in the editor:

No route matches [GET] "/datawrapper/main/pageflow/chart/scraped_sites/000/000/001/all.html"

I have the same configuration in my pageflow_chart.rb as you have. I think i struggle with the nginx proxy. Where exactly do i have to place this snippet
```
location /datawrapper/ {
  proxy_pass http://bucketname.s3-website-eu-west-1.amazonaws.com/;
  proxy_redirect http://bucketname.s3-website-eu-west-1.amazonaws.com/ $scheme://$host/datawrapper/;
}
```

i really hope for some help since you seem to be quite active in the pageflow community

thanks in advance
and best regards,
Ronald

**Comment by tilsammans** [comment]
Hi Ronald,

I've now put this in the [README](https://github.com/codevise/pageflow-chart/commit/6c4f012192d4bfb7126a954e7b54351b2e583a22)!
