### ISSUE TITLE
internal_links Mosaic not showing

### ISSUE THREAD

**Issue by RonFire** [scrollytelling/app#16]
Hey there,

i've installed a few page-types und plugins and have Problems with the internal_links mosaik page-type. I installed the internal_links page-type as explained in the tutorial but there is only the "Multiple Choice" page type showing. Do i have to do anything special to see the Mosaic page-type?

I think the same problem i have with the external link. I installed it as explained in the tutorial but there is no page-type visible

i have added my Gemfile and Gemfile.lock.
I hope you can help me on this one.

Best regards,
Ronald
[Gemfile.lock.txt](https://github.com/scrollytelling/app/files/1291421/Gemfile.lock.txt)
[Gemfile.txt](https://github.com/scrollytelling/app/files/1291420/Gemfile.txt)

**Comment by tf** [comment]
solved in codevise/pageflow-external-links#35
