### ISSUE TITLE
TypeError: pageflow.startEditor is not a function

### ISSUE THREAD

**Issue by tilsammans** [scrollytelling/app#18]
https://sentry.io/space-babies/scr/issues/363039003/

```
TypeError: pageflow.startEditor is not a function
  at None (/entries/vulkaan-bali/edit:83:12)
```

**Comment by tilsammans** [comment]
pinging @tf 

We got this JavaScript exception in production and I am not sure if it's noise or worth investigating. Could there be a scenario where `startEditor` is being called, but the function has not been defined yet?

**Comment by tf** [comment]
`startEditor` should [only ever be called from the `entries/edit` view](https://github.com/codevise/pageflow/blob/e5b160f9a76499e3f6584c11d3170ccf8f710527/app/views/pageflow/entries/edit.html.erb#L40) to start the editor. It not being defined, could hint at an earlier exception that happened while evaluating the Javascript files. I'd expect the editor not to start if that exception happens.

**Comment by tilsammans** [comment]
I've investigated, and this happens when the compiled editor.js could not be loaded.

So the exception is probably warranted.

**Comment by tilsammans** [comment]
Closing this issue, since (precompiled) editor.js is required.

We saw this after scaling up the front-ends and not doing a full asset precompile, leaving the new server with inconsistent filenames.
