### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by tilsammans** [scrollytelling/app#20]
https://sentry.io/space-babies/scr/issues/372496426/

```
TypeError: undefined is not a function
  at None (/entries/aleppo/edit)
```

**Comment by tilsammans** [comment]
We keep seeing a difference in compiled assets per server @tf 

Do you have any idea what causes this? For example, one of our front ends now has `pageflow/editor-7c0423562087cfcd4faa30d11eb47beb9d5c4af0fcc92e50644b901a20beb05f.js` but one of the others doesn't have this.

I have never seen this behaviour before, and it only started happening after the change to Pageflow 12. Is there some kind of special precompilation step I am missing?

**Comment by tf** [comment]
Hi Joost,

maybe you could outline a bit how your asset precompilation process works during deploy. 

Do the hashes in URLs match the hashes of files generated by the latest run of asset precompilation? Could caching be involved at some level: serving outdated HTML with urls still pointing to prior versions of the compiled asset?

If you'd prefer to talk about the specifics of your process in a non public setting, we can also take this discussion to mail if you want.

Tim

**Comment by tilsammans** [comment]
It's all completely standard Rails hosting stuff.

What I think is happening is that one or two servers are actually not altogether functioning properly. So I am rebuilding the entire stack on a different provider to see if the inconsistencies are there too. If they are, I will definitely report back. If they aren't, then I've had a case of a malfunctioning server.

**Comment by tilsammans** [comment]
Sorry to bother you @tf 

I completely rebuilt the hosting stack and the problem is gone.

I've been having unexplainable server problems on Digital Ocean for a while; maybe I am on a bad host or maybe something else is going on. The rebuilt stack behaves like I would expect and all the precompiled assets are in place. I guess this error was caused by a server having a bad day...
