### ISSUE TITLE
Swipe to hide text no longer works

### ISSUE THREAD

**Issue by tilsammans** [scrollytelling/app#28]
> Hi Joost, 
Een vraagje, het lijkt alsof de swipe functie van onze scrolly het niet goed doet. Eerst als je swipete, swipete je de tekst weg en bleef de foto staan zodat je de foto goed kon zien. (dat is wat we willen). Maar nu als je swipet raakt ie in de war of blijft de tekst gewoon staan. 
Is dat een bekend probleem of is er iets bij ons verkeerd gegaan? Zou jij eens willen kijken? Geen haast. 
<a href="https://stories.paxforpeace.nl/operating-under-fire" rel="nofollow">https://stories.paxforpeace.nl/operating-under-fire</a> 
Dank je wel alvast, 
Roos

**Link:** [Conversation with Roosie B.](https://app.intercom.com/a/apps/qhfgd73f/respond/inbox/all/conversations/12873154632)

**Customer:** [Roosie B.](https://app.intercom.com/a/apps/qhfgd73f/users/595e127cea4e437cedf0c0b8/all-conversations) from [Scrollytelling](https://app.intercom.com/a/apps/qhfgd73f/companies/5991b0d7516b8adda6dc32de)
**Customer ID:** 395997761
**Company ID:** 2
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/qhfgd73f/respond/inbox/all/conversations/12873154632) when this issue is closed.

**Comment by tilsammans** [comment]
@tf have you heard of this before? It's true, swiping no longer moves the text away.

The code _is_ part of the compiled bundle, though. And the page type and theme seem to be in order from what I can tell.

**Comment by tf** [comment]
Was not aware. Good find.
See https://github.com/codevise/pageflow/pull/919
